language: python

python:
  - "3.5"

node_js:
  - "5.3"

services:
  - mongodb

cache:
  directories:
    - node_modules
    - /home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages
    - pip

install:
  - "cd api; pip install -r requirements.txt; cd .."

before_script:
  - npm install

script:
  - gulp test
