language: python

python:
  - "3.5"

node_js:
  - "5.3"

services:
  - mongodb

cache:
  directories:
    - node_modules
    - api/env

install:
  - "cd api; pip install -r requirements.txt"

before_script:
  - npm install

script:
  - gulp test
