var ActionType = {
  TASKS: {
    TEXT_CHANGED_FROM_SERVER: 'TEXT_CHANGED_FROM_SERVER',
    TEXT_UPDATE_SUCCESS: 'TEXT_UPDATE_SUCCESS',
    GET_METADATA: 'GET_METADATA'
  }
}

export default ActionType;
